### ISSUE TITLE
How did you create model target A?!?!

### ISSUE THREAD

**Issue by MrDido** [vadel/AudioUniversalPerturbations#6]
Hi! I'm looking for the model target A in order to train it again. How did you created the network?!? What are the changes that you made starting from the tensorflow code?

Thank you in advance.

**Comment by vadel** [comment]
Hi, for future questions (@MrDido contacted me by email), I attach the "input_data.py" file, which is the one we adapted from the tf code to train the model, as well as the filterbank we used. We used the following parameters (set in train.py): 'feature_bin_count'=40,  'window_size_ms'=20 and 'window_stride_ms'=10.
[files.zip](https://github.com/vadel/AudioUniversalPerturbations/files/6523277/files.zip)
